#!/usr/bin/python

import os
import sys
import numpy as np

name = str(sys.argv[1])

namelist = []				
for file in os.listdir("kfcd/"):
    if name in file:
        namelist.append(file)

data = []
readyTag = 'KFCD: Finished at:'
enTag = 'TOT-PBE'
momTag = "Magnetic moment for IQ ="

for name in namelist:
    lineIndex = 0
    fl = open("kfcd/"+name)
    lines = fl.readlines()
    moms = []
    ready = False
    for line in lines:
        if readyTag in line:
            ready = True
    if ready:
        for line in lines:
            if enTag in line:
                linesplit = line.split()
                sws = float(linesplit[6])
            if momTag in line:
                linesplit = line.split()
                moms.append(float(linesplit[7]))
        lineIndex += 1

        sws_moms = []
        sws_moms.append(sws)
        for i in range(len(moms)):
            sws_moms.append(moms[i])
        data.append(sws_moms)
    fl.close()

#for i in range(len(data)):
#    print(data[i])


data = np.asarray(data)
# Make sure datapoints are in ascending order
data = data[data[:,0].argsort()]

data_len = len(data[0,:])

format = ""

for i in range(data_len):
    format = format + "{0}{1}{2}{3} ".format("{",i,":9.6f","}")

for i in range(len(data[:,0])):
    print(format.format(*data[i,:]))

