#!/usr/bin/python

import os
import sys

# Help python to find the pyemto folder
sys.path.insert(0, "/home/hpleva/pyemto")
from pyemto.utilities.utils import run_emto

job = str(sys.argv[1])

run_emto(job)
